# LINEAR REGRESSION MODEL

In [1]:
import pandas as pd


In [2]:
import numpy as np 
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import fetch_california_housing

In [11]:
df=pd.read_csv('Boston1.csv')

In [12]:
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression #fit and predict
from sklearn.metrics import  r2_score , mean_squared_error , mean_absolute_error

In [20]:
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [ ]:
#select data for modeling

In [21]:
df_selected= df[['rm', 'ptratio','lstat','medv']]
df_selected.head(2)


rm  ptratio  lstat  medv
0  6.575     15.3   4.98  24.0
1  6.421     17.8   9.14  21.6

In [ ]:
# refer stats model selection

In [22]:
x=df_selected[['rm', 'ptratio','lstat']]
y=df_selected[['medv']]
print(x.shape)
print(y.shape)


(506, 3)
(506, 1)


In [27]:
# split the data into train and test data
x_train, x_test , y_train , y_test = train_test_split(x,y, test_size = 0.3 , random_state=42)


In [23]:
#configuring the model
model=LinearRegression()
model

LinearRegression()

In [41]:
#fit the model
lm=model.fit(x_train, y_train)

In [30]:
lm.coef_   #b0,b1,b2

array([[ 4.46162598, -0.86290452, -0.60815   ]])

In [32]:
lm.intercept_  #constant

array([18.11908505])

In [36]:
#predict the train data
y_train_predict=lm.predict(x_train)
y_train_predict[:10]

array([[27.50256404],
       [22.9922606 ],
       [21.81484141],
       [22.47621327],
       [16.10224974],
       [24.49640822],
       [31.4172681 ],
       [12.06854712],
       [22.2145967 ],
       [18.7368882 ]])

In [37]:
#predict the test data
y_test_predict=lm.predict(x_test)
y_test_predict[:10]

array([[26.92298627],
       [30.93686434],
       [16.47934188],
       [25.25409179],
       [18.28052198],
       [22.71776451],
       [17.48030837],
       [12.67868396],
       [20.65299142],
       [19.72674849]])

In [38]:
#evaluation the  model----r squared, mean squared error for train data
rsq = r2_score(y_train, y_train_predict)
print(f'r squared value for train data is { rsq } ')
mse= mean_squared_error(y_train , y_train_predict )
print(f'mean squared value for train data  is {mse}' )

# root mean squared 

rmse = np.sqrt(mse)
print(f'root mean squared error of train data is { rmse} ')

r squared value for train data is 0.6850018441906278 
mean squared value for train data  is 27.687244667341563
root mean squared error of train data is 5.261867032464956 


In [40]:
# metrics for test data 
rsq=r2_score(y_test , y_test_predict)
print(f'r squared value for  the test data is {rsq}')
mse= mean_squared_error(y_test , y_test_predict)
print(f'mean squared value for test data is {mse}')
rmse=np.sqrt(mse)
print(f'root mean squared error of test data is {rmse} ')

r squared value for  the test data is 0.650904156861472
mean squared value for test data is 26.01221192212626
root mean squared error of test data is 5.100216850500208 


In [42]:
x_train.head()

rm  ptratio  lstat
5    6.430     18.7   5.21
116  6.176     17.8  12.04
45   5.682     17.9  10.21
16   5.935     21.0   6.58
468  5.926     20.2  18.13

In [46]:
import warnings
warnings.filterwarnings('ignore')

In [47]:
#how  to predict for new data 
x_new = [7.5,19,7]
y_new_predict  = lm.predict([x_new])
y_new_predict

array([[30.92904398]])

In [51]:
rm = int(input("enter the number of rooms: "))
lstat = int(input("enter the lower status of the population: "))
ptratio = int(input("enter the pupil teacher ratio: "))
x_new=[rm, lstat , ptratio ]
y_new_predict=lm.predict([x_new])
print(f' the predicted price  of the house is {y_new_predict}')

enter the number of rooms:  5
enter the lower status of the population:  15
enter the pupil teacher ratio:  20


 the predicted price  of the house is [[15.3206471]]


In [50]:
x_new=[rm, lstat , ptratio ]
y_new_predict=lm.predict([x_new])
print(f' the predicted price  of the house is {y_new_predict}')

 the predicted price  of the house is [[10.85902111]]


In [ ]:
# predicting the price --- linear regression , dt regressor , df  regressor , choose the mode that gives that gives the best metrics ...higher r2 and lower rsme

In [52]:
df.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

In [56]:
df_new = df[['rm','ptratio','lstat','age','medv']]
x=df_new[['rm','ptratio','lstat','age']]
y=df_new[['medv']]
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size=0.30 , random_state=42)
model_new=LinearRegression()
lm_new=model_new.fit(x_train , y_train)
y_train_predict_new=lm_new.predict(x_train)
y_test_predict_new = lm_new.predict(x_test)
rsq_train = r2_score(y_train, y_train_predict_new)
print("R squared value for train data:",rsq_train)
mse_train = mean_squared_error(y_train, y_train_predict_new)
print("Mean squared error for train data:",mse_train)
rsq_test = r2_score(y_test, y_test_predict_new)
print("R squared value for test data:",rsq_test)
mse_test = mean_squared_error(y_test, y_test_predict_new)
print("Mean squared error for train data:",mse_test)

R squared value for train data: 0.6862400587712391
Mean squared error for train data: 27.578409903036466
R squared value for test data: 0.6535867872663021
Mean squared error for train data: 25.812320826397887


In [58]:
import statsmodels.api as  sm

In [60]:
x=df[['rm','lstat','ptratio']]
y=df['medv']
x=sm.add_constant(x)
x

const     rm  lstat  ptratio
0      1.0  6.575   4.98     15.3
1      1.0  6.421   9.14     17.8
2      1.0  7.185   4.03     17.8
3      1.0  6.998   2.94     18.7
4      1.0  7.147   5.33     18.7
..     ...    ...    ...      ...
501    1.0  6.593   9.67     21.0
502    1.0  6.120   9.08     21.0
503    1.0  6.976   5.64     21.0
504    1.0  6.794   6.48     21.0
505    1.0  6.030   7.88     21.0

[506 rows x 4 columns]

In [63]:
x=df[['rm','lstat','ptratio']]
y=df['medv']
x=sm.add_constant(x)
#call the representative model and give the input 
model=sm.OLS(y,x)
results=model.fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                   medv   R-squared:                       0.679
Model:                            OLS   Adj. R-squared:                  0.677
Method:                 Least Squares   F-statistic:                     353.3
Date:                Sat, 29 Nov 2025   Prob (F-statistic):          2.69e-123
Time:                        11:45:44   Log-Likelihood:                -1553.0
No. Observations:                 506   AIC:                             3114.
Df Residuals:                     502   BIC:                             3131.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         18.5671      3.913      4.745      0.0

In [ ]:
classification problem cannot  be solved  using linear regression regression 
it can be solved using logistic regression