# Logistic Tegression Model

# Import Libraries

In [2]:
import pandas as pd 
import numpy as np 
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
import matplotlib.pyplot as plt 
from  sklearn.model_selection import   train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report , confusion_matrix ,accuracy_score
from ydata_profiling import ProfileReport 



# Reading Dataset

In [3]:
df=pd.read_csv('heart1.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  target  
0   0       1  
1   0       1  
2   0       1  
3   0       1  
4   0       1

# Creating Profile Report

In [4]:
profile=ProfileReport(df, title='Heart Report')

In [5]:
profile.to_file('Heart_Report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


%|                                                                                           | 0/13 [00:00<?, ?it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 94.58it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
x=df.drop('target', axis=1)#-----independent variable 
y=df[['target']]#----dependent variable

In [7]:
x.head(1)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   

   ca  
0   0

In [8]:
y.head(1)

target
0       1

In [9]:
#split train test
x_train , x_test , y_train , y_test = train_test_split ( x , y , test_size=0.30 , random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(212, 12)
(91, 12)
(212, 1)
(91, 1)


In [10]:
# configure the model and  train the model using train data
log_reg=LogisticRegression()
model= log_reg.fit(x_train , y_train )

In [11]:
y_train_predict=model.predict(x_train)
y_train_predict[:10]

array([1, 1, 1, 1, 0, 1, 0, 1, 0, 1])

In [12]:
y_test_predict=model.predict(x_test)
y_test_predict[:10]

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 0])

In [13]:
# evaluate the  module 
print(confusion_matrix(y_train, y_train_predict))
print(classification_report (y_train, y_train_predict))
print(accuracy_score(y_train , y_train_predict))

[[ 74  23]
 [ 14 101]]
              precision    recall  f1-score   support

           0       0.84      0.76      0.80        97
           1       0.81      0.88      0.85       115

    accuracy                           0.83       212
   macro avg       0.83      0.82      0.82       212
weighted avg       0.83      0.83      0.82       212

0.8254716981132075


In [14]:
print(confusion_matrix(y_test, y_test_predict))
print(classification_report(y_test, y_test_predict))
print(accuracy_score(y_test, y_test_predict))

[[36  5]
 [ 9 41]]
              precision    recall  f1-score   support

           0       0.80      0.88      0.84        41
           1       0.89      0.82      0.85        50

    accuracy                           0.85        91
   macro avg       0.85      0.85      0.85        91
weighted avg       0.85      0.85      0.85        91

0.8461538461538461
