In [ ]:
# 1. Create a list named ‘myList’ that has the following elements: 10, 20, 30,
# ‘apple’, True, 8.10:
# a. Now in the ‘myList’, append these values: 30, 40
# b. After that, reverse the elements of the ‘myList’ and store that in
# ‘reversedList’
# 2. Create a dictionary with key values as 1, 2, 3 and the values as ‘data’,
# ‘information’ and ‘text’:
# a. After that, eliminate the ‘text’ value from the dictionary
# b. Add ‘features’ in the dictionary
# c. Fetch the ‘data’ element from the dictionary and display it in the output
# 3. Create a tuple and add these elements 1, 2, 3, apple, mango in my_tuple.
# 4. Create another tuple named numeric_tuple consisting of only integer
# values 10, 20, 30, 40, 50:
# a. Find the minimum value from the numeric_tuple
# b. Concatenate my_tuple with numeric_tuple and store the result in r1
# c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’
# 5. Create 2 sets with the names set1 and set2, where set1 contains
# {1,2,3,4,5} and set2 contains {2,3,7,6,1}
# Perform the below operation:
# a. set1 union set2
# b. set1 intersection set2
# c. set1 difference set2

In [14]:
# 1. Create a list named ‘myList’ that has the following elements: 10, 20, 30,
# ‘apple’, True, 8.10:
# a. Now in the ‘myList’, append these values: 30, 40
# b. After that, reverse the elements of the ‘myList’ and store that in
# ‘reversedList’

myList=[10,20,30,"apple",True ,8.10]
myList.append(30)
myList.append(40)
print(myList)




[10, 20, 30, 'apple', True, 8.1, 30, 40]


In [17]:
myList=[10, 20, 30, 'apple', True, 8.1, 30, 40]
reversedList=myList[::-1]
print(reversedList)



[40, 30, 8.1, True, 'apple', 30, 20, 10]


In [4]:
# 2. Create a dictionary with key values as 1, 2, 3 and the values as ‘data’,
# ‘information’ and ‘text’:
# a. After that, eliminate the ‘text’ value from the dictionary
# b. Add ‘features’ in the dictionary
# c. Fetch the ‘data’ element from the dictionary and display it in the output

myDict = {1: "data", 2: "information", 3: "text"}
del myDict[3]   

myDict[3] = "features"

print(myDict)
myDict.get(1)


{1: 'data', 2: 'information', 3: 'features'}


'data'

In [7]:
# 3. Create a tuple and add these elements 1, 2, 3, apple, mango in my_tuple.
my_tuple=(1,2,3, "apple" , "mango" )
print(my_tuple)

(1, 2, 3, 'apple', 'mango')


In [17]:
 # 4. Create another tuple named numeric_tuple consisting of only integer
# values 10, 20, 30, 40, 50:
# a. Find the minimum value from the numeric_tuple
# b. Concatenate my_tuple with numeric_tuple and store the result in r1
# c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’
numeric_tuple= (10,20,30,40,50)
my_tuple=(1,2,3, "apple" , "mango" )
a=min(numeric_tuple)
print(a)
r1=my_tuple+numeric_tuple
print(r1)
newdupli=2*my_tuple
print(newdupli)

10
(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)
(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')


In [20]:
# 5. Create 2 sets with the names set1 and set2, where set1 contains
# {1,2,3,4,5} and set2 contains {2,3,7,6,1}
# Perform the below operation:
# a. set1 union set2
# b. set1 intersection set2
# c. set1 difference set2

set1={1,2,3,4,5}
set2={2,3,7,6,1}
print(set1.union(set2))
print(set1.intersection(set2))
print(set1.difference(set2))

{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3}
{4, 5}


In [ ]:
# . Create a 3x3 matrix array with values ranging from 2 to 10.
# 2. Create a NumPy array having user input values and convert the integer
# type to the float type of the elements of the array. For instance: Original
# array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]
# 3. Write a NumPy program to append values to the end of an array. For
# instance: Original array: [10, 20, 30] . After that, append values to the end
# of the array: [10 20 30 40 50 60 70 80 90]
# 4. Create two NumPy arrays and add the elements of both the arrays and
# store the result in sumArray.
# 5. Create a 3x3 array having values from 10-90 (interval of 10) and store that
# in array1
# Perform the following tasks:
# a. Extract the 1st row from the array
# b. Extract the last element from the array

In [3]:
# . Create a 3x3 matrix array with values ranging from 2 to 10.
import numpy as np 
arr=np.random.randint(2,10, size=(3,3))
print(arr)

[[5 9 8]
 [7 2 7]
 [8 2 4]]


In [ ]:
# 2. Create a NumPy array having user input values and convert the integer
# type to the float type of the elements of the array. For instance: Original
# array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]
a=int(input("enter the int value here:   "))
b=int(input("enter the int  value here:   "))
arr=np.array([a,b],dtype=float)
print(arr)


In [31]:
# 3. Write a NumPy program to append values to the end of an array. For
# instance: Original array: [10, 20, 30] . After that, append values to the end
# of the array: [10 20 30 40 50 60 70 80 90]
#i have taken given example only 
arr=np.array([10, 20, 30])
arr1=np.array([40,50,60,70,80,90])
a=np.concatenate((arr,arr1))
print(a)

[10 20 30 40 50 60 70 80 90]


In [33]:
# 4. Create two NumPy arrays and add the elements of both the arrays and
# store the result in sumArray.

arr=np.array([10, 20, 30])
arr1=np.array([40,50,60])
arr2= arr+arr1
print(arr2)

[50 70 90]


In [56]:
# 5. Create a 3x3 array having values from 10-90 (interval of 10) and store that
# in array1
# Perform the following tasks:
# a. Extract the 1st row from the array
# b. Extract the last element from the array
array1=np.random.randint(10,90, size= (3,3))
array1


array([[29, 40, 50],
       [55, 29, 38],
       [40, 36, 88]])

In [64]:
print(array1[2,2])
print(array1[0])

88
[29 40 50]


In [ ]:
#case study
1. Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric
value and returns a NumPy array of the given dimension filled with the
given value e.g.: solve((3, 3), 5) will return
[
[5, 5, 5],
[5, 5, 5],
[5, 5, 5]
]
2. Create a method that takes n NumPy arrays of the same dimensions,
sums them and returns the answer.
3. Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
top-left N X M sub matrix, e.g:
[
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
]
top_left_sub_matrix (matrix, 2, 2) -> should return:
[
[1, 2]
[4, 5]


In [3]:
# 1. Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric
# value and returns a NumPy array of the given dimension filled with the
# given value e.g.: solve((3, 3), 5) will return
# [
# [5, 5, 5],
# [5, 5, 5],
# [5, 5, 5]

def createnum(a,b):
    return np.full(a,b)
print(createnum((3,3),7))

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [1]:
# 2. Create a method that takes n NumPy arrays of the same dimensions,
# sums them and returns the answer.
import numpy as np
def sum(*arr):
    return np.sum(arr, axis=1) # i have created this for columns only same way we can do for rows but we need to change the axis=0
a=np.array([[1,2,3],[5,6,7]])
b=np.array([[8,9,10],[11,12,13]])
obj=sum(a,b)
print(obj)


[[ 6  8 10]
 [19 21 23]]


In [2]:
# 3. Given a 2 D Array of N X M Dimension, write a function that accepts this
# array as well as two numbers N and M. The method should return the
# top-left N X M sub matrix, e.g:
# [
# [1, 2, 3],
# [4, 5, 6],
# [7, 8, 9],
# ]
# top_left_sub_matrix (matrix, 2, 2) -> should return:
# [
# [1, 2]
# [4, 5]]

def matrix(matrix,n,m):
  return[row[:m] for row in matrix[:n]]

matrix1=[[1,2,3],[4,5,6],[7,8,9]]
result=matrix(matrix1,2,2)
print(result)



[[1, 2], [4, 5]]
